Added `realted postions` functionality
hiqdev/yii2-cart pull request #20
Opened 2020-03-16 16:07 UTC by tafid

2020-03-17 09:12 UTC, SilverFire requested changes
Надо ещё подтюнить удаление из корзины основного товара

2020-03-17 09:12 UTC, SilverFire commented on src/ShoppingCart.php
> +            if (!$position->hasParent()) {
Эксепшн на классах, которые не реализуют RelatedPositionInterface

2020-03-17 09:12 UTC, SilverFire commented on src/ShoppingCart.php
> +            if ($position->hasParent() && $position->parent_id === $parent->getCalculationModel()->calculation_id) {
Эксепшн на классах, которые не реализуют RelatedPositionInterface

2020-03-17 09:12 UTC, SilverFire commented on src/views/cart/index.php
> +                        return ['class' => 'hidden'];
Подумай, может лучше в DataProvider исключить эти строки заранее?

2020-03-17 09:12 UTC, SilverFire commented on src/widgets/views/CartTeaser.php
> +                    return !$position->hasParent();
эксепшн на классах которые не реализуют CartPositionInterface

2020-03-17 17:10 UTC, tafid commented on src/ShoppingCart.php
> +            if (!$position->hasParent()) {
Все будет норм, не будет эксепшена

2020-03-17 17:10 UTC, tafid commented on src/ShoppingCart.php
> +            if ($position->hasParent() && $position->parent_id === $parent->getCalculationModel()->calculation_id) {
Все будет норм, не будет эксепшена

2020-03-17 17:10 UTC, tafid commented on src/widgets/views/CartTeaser.php
> +                    return !$position->hasParent();
Все будет норм, не будет эксепшена

2020-03-18 13:58 UTC, SilverFire requested changes

2020-03-18 13:58 UTC, SilverFire commented on src/RelatedPosition.php
> +use hipanel\modules\finance\logic\Calculator;
yii2-cart не должен иметь зависимость на hipanel-module-finance

2020-03-18 13:58 UTC, SilverFire commented on src/RelatedPosition.php
> +        $calculationId = $position->getCalculationModel()->calculation_id;
Этот метод из `CalculableModelInterface`, а не из `CartPositionInterface`. Весь класс напрашивается на вынос в hipanel-module-finance

2020-03-18 13:58 UTC, SilverFire commented on src/RelatedPositionInterface.php
> +interface RelatedPositionInterface
Опиши в двух словах, что это за интерфейс

2020-03-18 13:58 UTC, SilverFire commented on src/ShoppingCart.php
> +            if ($position->hasParent() && $position->parent_id === $parent->getCalculationModel()->calculation_id) {
`getCalculationModel()` – это метод из `CalculableModelInterface`, его нельзя тут использовать.

Используй просто `$parent->getId()`, этого должно быть достаточно по идее.

2020-03-18 13:58 UTC, SilverFire commented on src/controllers/CartController.php
> +                return !$position->hasParent();
Подобный код есть копи-пастой уже в трёх местах этого PR. Предлагаю создать метод `ShoppingCart::getRootPositions()`

2020-03-19 15:30 UTC, SilverFire approved these changes

2020-03-19 16:18 UTC, tafid commented
> Надо ещё подтюнить удаление из корзины основного товара

подрюнил, когда удаляешь основной, добавлен бихейвр который удалит "сопутствующий"

2020-03-19 17:33 UTC, SilverFire approved these changes

2020-03-19 17:33 UTC, merged